to_do_list/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(
        "", include(
            "todolist.urls",
            namespace="todolist", )
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todolist/urls.py
from django.urls import path

from todolist.views import (
    index,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDoneView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "task/update/<int:pk>/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/delete/<int:pk>/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "task/done/<int:pk>/",
        TaskDoneView.as_view(),
        name="task-done"
         ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tags"
    ),
    path(
        "tag/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tag/update/<str:name>/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tag/delete/<str:name>/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
]

app_name = "todolist"

todolist/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks")

    class Meta:
        ordering = ["done", "datetime"]

    def __str__(self):
        return self.content

todolist/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404

from todolist.models import Task, Tag


def index(request):
    task_list = Task.objects.all()
    return render(request, "todolist/index.html", {"task_list": task_list})


class TaskDetailView(generic.DetailView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todolist:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todolist:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todolist:index")


class TaskDoneView(generic.UpdateView):
    model = Task
    fields = ["done"]
    template_name = "todolist/task_done.html"

    def get_object(self, queryset=None):
        task = super().get_object(queryset)
        task.done = not task.done
        task.save()
        return task

    def get_success_url(self):
        return reverse_lazy("todolist:index")


class TagListView(generic.ListView):
    model = Tag
    template_name = "todolist/tags.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todolist:tags")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todolist:tags")

    def get_object(self, queryset=None):
        return get_object_or_404(Tag, name=self.kwargs["name"])


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todolist:tags")

    def get_object(self, queryset=None):
        return get_object_or_404(Tag, name=self.kwargs["name"])

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>To do list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  <!-- Add additional CSS in static file -->
  {% load static %}

</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}{% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todolist:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todolist:tags' %}">Tags</a></li>
</ul>

templates/todolist/index.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="fw-bold">TO DO LIST</h1>
    <a href="{% url 'todolist:task-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </div>

  <div class="task-list">
    {% for task in task_list %}

      <div class="task-item mb-4 p-3 rounded">
        <div class="d-flex justify-content-between">
    <span class="bold-black-text mr-2">{{ task }}</span>
    {% if task.done %}
        <span class="bold-green-text">Done</span>
        <a href="{% url 'todolist:task-done' pk=task.id %}" class="btn btn-secondary link-to-page ml-auto">
            Undo
        </a>
    {% else %}
        <span class="bold-red-text">Not Done</span>
        <a href="{% url 'todolist:task-done' pk=task.id %}" class="btn btn-success link-to-page ml-auto">
            Complete
        </a>
    {% endif %}
</div>
      
        <p>
          <strong>Created:</strong> {{ task.datetime }}<br>

        <div class="task-actions">

          <div class="task-tags">
            Tags:
            {% for tag in task.tags.all %}
              <span class="tag-name">{{ tag.name }}</span>
            {% endfor %}
          </div>

          <a href="{% url 'todolist:task-update' pk=task.id %}" class="btn btn-link">Update</a>
          <a href="{% url 'todolist:task-delete' pk=task.id %}" class="btn btn-link">Delete</a>

        </div>
        <hr>
      </div>
    {% empty %}
      <p>No tasks available.</p>
    {% endfor %}
  </div>

{% endblock %}

templates/todolist/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4 main-content" style="padding-top: 100px;">
    <h3>Delete tag</h3>
    <p>Are you sure you want to delete this tag?</p>
    <form action="" method="post" class="mt-3">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger me-2">Yes</button>
      <a class="btn btn-primary" href="{% url 'todolist:index' %}">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/todolist/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todolist/tags.html
{% extends "base.html" %}

{% block content %}
  <h1>Tag</h1>
  <a href="{% url 'todolist:task-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>NAME</th>
        <th>UPDATE</th>
        <th>DELETE</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todolist:tag-update' tag.name %}">UPDATE</a>
          </td>
          <td>
            <a href="{% url 'todolist:tag-delete' tag.name %}">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no manufacturers in the service.</p>
  {% endif %}
{% endblock %}

templates/todolist/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4 main-content" style="padding-top: 100px;">
    <h3>Delete task</h3>
    <p>Are you sure you want to delete this task?</p>
    <form action="" method="post" class="mt-3">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger me-2">Yes</button>
      <a class="btn btn-primary" href="{% url 'todolist:index' %}">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/todolist/task_done.html
{% extends "base.html" %}

{% block content %}
  <h1>Task status changed</h1>

  <a href="{% url 'todolist:index' %}">Go back to the task list</a>
{% endblock %}

templates/todolist/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}